# Generated by Django 3.0.3 on 2020-04-05 14:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='catageory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=product.models.upload_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=120)),
                ('colorCode', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rate', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999), django.core.validators.MinValueValidator(1)])),
                ('shortDescription', models.TextField()),
                ('longDescription', models.TextField()),
                ('Introduction', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=product.models.upload_image_path)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('catageoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.catageory')),
            ],
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='subCatageory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=product.models.upload_image_path)),
                ('catageoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.catageory')),
            ],
        ),
        migrations.CreateModel(
            name='productSerial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductSerial', models.CharField(max_length=120)),
                ('mrp', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999), django.core.validators.MinValueValidator(1)])),
                ('purchaseDate', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('catageoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.catageory')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.size')),
                ('subCatageoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subCatageory')),
            ],
        ),
        migrations.CreateModel(
            name='productImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to=product.models.upload_image_path)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('catageoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.catageory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('productSerial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productSerial')),
                ('subCatageoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subCatageory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subCatageoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subCatageory'),
        ),
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('percentage', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fromDate', models.DateTimeField()),
                ('toDate', models.DateTimeField()),
                ('maxDiscount', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)])),
                ('catageoryId', models.ManyToManyField(to='product.catageory')),
                ('product', models.ManyToManyField(to='product.product')),
                ('subCatageoryId', models.ManyToManyField(to='product.subCatageory')),
            ],
        ),
    ]
