# Generated by Django 3.0.3 on 2020-04-05 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductRate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999), django.core.validators.MinValueValidator(1)]),
        ),
    ]
