# Generated by Django 3.0.6 on 2020-05-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_productrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catageoryId',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='catageoryId',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='productSerial',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='subCatageoryId',
        ),
        migrations.RemoveField(
            model_name='productserial',
            name='catageoryId',
        ),
        migrations.RemoveField(
            model_name='productserial',
            name='subCatageoryId',
        ),
        migrations.AddField(
            model_name='size',
            name='name',
            field=models.CharField(default='Size', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='subCatageoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcatageory', to='product.subCatageory'),
        ),
        migrations.AlterField(
            model_name='productserial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product'),
        ),
        migrations.AlterField(
            model_name='subcatageory',
            name='catageoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catageory', to='product.catageory'),
        ),
    ]
