# Generated by Django 3.0.6 on 2020-05-28 15:24

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200528_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='catageory',
            name='largeImage',
            field=models.ImageField(blank=True, upload_to=product.models.upload_image_path),
        ),
    ]
