# Generated by Django 3.0.6 on 2020-05-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_catageory_largeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcatageory',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
