# Generated by Django 3.0.6 on 2020-05-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_subcatageory_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcatageory',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
