# Generated by Django 3.0.6 on 2020-06-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200528_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(default=None, editable=False, upload_to='thumbs/<function upload_image_path at 0x000002075E62EAF0>'),
            preserve_default=False,
        ),
    ]
