# Generated by Django 3.0.3 on 2020-02-29 14:55

import customModels.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=customModels.models.upload_image_path)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('typeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customModels.commonTypes')),
            ],
        ),
    ]
