# Generated by Django 3.0.3 on 2020-03-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customModels', '0002_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='common',
            name='value1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='common',
            name='value2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='common',
            name='value3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
