# Generated by Django 3.0.6 on 2020-05-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customModels', '0003_auto_20200301_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='typeName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common', to='customModels.commonTypes'),
        ),
    ]
