# Generated by Django 3.0.6 on 2020-05-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customModels', '0004_auto_20200529_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='Name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='commontypes',
            name='typeName',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
